version: '3'

services: 
  mysql:
    image: mysql:5.6
    environment:
      - MYSQL_ROOT_PASSWORD=hardpassword
      - MYSQL_DATABASE=firebasegateway
      - MYSQL_USER=uFirebaseGateway 
      - MYSQL_PASSWORD=1111
    ports:
      - 3307:3306
  firebase-gateway:
    image: mspandrade/firebase-gateway
    depends_on:
      - mysql
    ports:
      - 8080:8080
    environment:
      - DATABASE_HOST=mysql
      - DATABASE_USER=uFirebaseGateway
      - DATABASE_PASSWORD=1111
      - DATABASE_NAME=firebasegateway  
      - DATABASE_PORT=3307
      - JDK_JAVA_OPTIONS='-Dspring.datasource.password=$DATABASE_PASSWORD -Dspring.datasource.url=jdbc:mysql://$DATABASE_HOST:$DATABASE_PORT/$DATABASE_NAME?useSSL=false'